name: release
on:
  push:
    tags:
      - 'v*'
jobs:
  buildapp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp: [sbcl-bin]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install libraries that cannot be installed with quicklisp
        run: |
          ros install massung/lexer
